version: '3'
services:
  mongors:
    image: mongo
    container_name: mongors
    hostname: mongors
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/outvio/mongodb/data/db:/data/db
      - ../scripts/rs-init.js:/scripts/rs-init.js
    healthcheck:
      test: mongosh --quiet --eval "rs.status().ok"
      interval: 10s
      start_period: 10s
    command: ["--replSet", "test", "--bind_ip_all"]
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/outvio/redis:/data